version: "3.8"
services:
  node-app:
    build:
      context: ./node-app
      dockerfile: Dockerfile-node
    container_name: node_app
    ports:
      - "3000:3000"
    networks:
      - backend

  server:
    build:
      context: ./server
      dockerfile: Dockerfile-server
    container_name: sensor_server
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - mongodb
      - redis
      - node-app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - backend

networks:
  backend:
    driver: bridge
